### ISSUE TITLE
Deploy NFT contract errors

### ISSUE THREAD

**Issue by laukkw** [matter-labs/zksync-v2-issues#14] opened 2022-10-14 02:41 UTC
1. Before being updated, the contract was successfully compiled with ZKSOLC V1.1.6 and successfully deployed,The rest of the contract deployment was also successful
2. After the update, I did the following operations
3. `rm -rf artifacts-zk cache-zk`  
4. `yarn add -D typescript ts-node ethers zksync-web3 hardhat @matterlabs/hardhat-zksync-solc @matterlabs/hardhat-zksync-deploy`
5. Replace ZKSOLC from V1.1.6 to V1.2.0
6. The following error when I deploy
![1 2 0](https://user-images.githubusercontent.com/34640369/195749574-1cc3d6f0-a917-4ca5-ad8f-296db6eccdbf.png)
7. When I switch back to 1.1.6, it will also be wrong
![1 6 0](https://user-images.githubusercontent.com/34640369/195749904-bb87aa2f-58ab-466f-a7a4-15d43ed231ea.png)

Please help me see why? please

**Comment by bxpana** [comment] 2022-10-14 22:35
@laukkw we put out some updates today. Can you please try again? If that doesn't work can you please share your `hardhat.config.ts` and `package.json` files or the content of the files? We would also need a reproducible code example to further investigate

**Comment by deanpress** [comment] 2022-10-16 18:07
Can reproduce the same issue with custom contracts, even ones modified from the Greeter example. It seems that there's a big error rate when deploying contracts with shared contract/library imports and function overrides.

**Comment by laukkw** [comment] 2022-10-17 02:27
I tried again and failed. The description of the problem is the same as before

**Comment by laukkw** [comment] 2022-10-17 02:29
`require("@matterlabs/hardhat-zksync-deploy");
require("@matterlabs/hardhat-zksync-solc");

module.exports = {
  zksolc: {
    version: "0.3.8",
    compilerSource: "docker",
    settings: {
      optimizer: {
        enabled: true,
      },
      experimental: {
          dockerImage: "matterlabs/zksolc",
          tag: "v1.2.0"
      },
    },
  },
  zkSyncDeploy: {
    zkSyncNetwork: "https://zksync2-testnet.zksync.dev",
    ethNetwork: "goerli", // Can also be the RPC URL of the network (e.g. `https://goerli.infura.io/v3/<API_KEY>`)
  },
  networks: {
    hardhat: {
      zksync: true,
    },
  },
  solidity: {
      version: "0.8.16",
      settings: { // setting of compile, optional
          optimizer: {  // setting of optimizing
              enabled: true,
              runs: 200
          }
      }
  }
};`


`{
  "name": "greeter-front-end",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@matterlabs/hardhat-zksync-deploy": "^0.5.1",
    "@matterlabs/hardhat-zksync-solc": "^0.3.9",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "ethers": "^5.7.1",
    "hardhat": "^2.12.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4",
    "vue-template-compiler": "^2.6.11",
    "zksync-web3": "^0.11.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ],
  "main": "index.js",
  "repository": "https://github.com/bobjiang/zkSync-examples.git",
  "author": "rzry <1319339638@qq.com>",
  "license": "MIT"
}
`

**Comment by laukkw** [comment] 2022-10-17 02:31
![package](https://user-images.githubusercontent.com/34640369/196076573-5f9f7955-c286-40c4-a28a-efc85edbc67b.png)
![config](https://user-images.githubusercontent.com/34640369/196076582-057a5e12-b216-443d-a703-89468821d6a6.png)

**Comment by bxpana** [comment] 2022-10-17 21:17
@laukkw in your `hardhat.config.ts` you are using a very outdated `zksolc` version.

That should be `1.2.0` and can you also try `compilerSource` as `"binary"` instead of `"docker"`?

**Comment by laukkw** [comment] 2022-10-18 05:51
@bxpana Because it was compiled using 'Docker' . I recompiled using 'binary' , but it still failed.
![ts](https://user-images.githubusercontent.com/34640369/196346467-6f99a4dc-c898-4387-b913-cc7715d491b3.png)
![err](https://user-images.githubusercontent.com/34640369/196346492-92c5ce34-4c2d-40eb-866b-8f14bcb3b01c.png)

**Comment by deanpress** [comment] 2022-10-19 15:58
I have experienced the same issues and outlined all actions taken in this thread, including rewriting a new contract using zkSync's greeter example:

I can confirm deployment issues with contracts that have shared dependencies and a constructor in the main entry contract. If you have contracts Shared and A is Shared + B is Shared, and then a contract Main is A, B with constructor logic.

Also, the contract will deploy if you have no constructor logic, or if you have the constructor logic but no dependencies. But never if you have both shared dependencies and constructor logic. 

There seem to be many cases of solidity logic that trigger this deployment error, rendering most types of contract deployments on testnet impossible at the moment.

**Comment by bxpana** [comment] 2022-10-19 23:51
@laukkw Thanks for the additional details and thank you @deanpress for the deep dive. I'll get this to the team to check out ASAP

**Comment by laukkw** [comment] 2022-10-20 02:10
I removed some of the helper functions, such as query modification, and so on..The contract is successfully deployed.. So I'm not sure if it's really about constructors or whether it's about contract length

**Comment by StanislavBreadless** [comment] 2022-10-20 07:28
@deanpress I deployed the following `Main` contract without a problem:

Main.sol:

```
pragma solidity ^0.8.0;

import "./A.sol";
import "./B.sol";

contract Main is A,B {
    constructor() {
        foo();
        bar();
    }
}
```
A.sol:
```
pragma solidity ^0.8.0;

import "./Shared.sol";

contract A is Shared {
    function foo() public {
        util();
    }
}
```
B.sol
```
pragma solidity ^0.8.0;

import "./Shared.sol";

contract B is Shared {
    function bar() public {
        util();
    }
}
```
Shared.sol
```
pragma solidity ^0.8.0;

contract Shared {
    function util() public {
        assembly {
            sstore("myslot", 12)
        }
    }
}
```

Could you please provide a minimal reproducible example?

**Comment by deanpress** [comment] 2022-10-20 15:03
Have you tried using solc 0.8.17? This is pretty identical to what I had. But I also had a contract that I was able to deploy successfully previously that later gave the same call exception on re-deploy.

**Comment by deanpress** [comment] 2022-10-22 13:45
> I removed some of the helper functions, such as query modification, and so on..The contract is successfully deployed.. So I'm not sure if it's really about constructors or whether it's about contract length

Another user with the same issue confirmed that it worked after reducing contract size by splitting up the contract into separate external ones, so I think we can safely conclude that the network's contract size limit is lower than it should be.

**Comment by amrshaban2005** [comment] 2022-10-24 06:41
for me I have 5 contracts get this error and  the size of them as following 
18.19 KB
18.81 KB
22.34 KB
22.15 KB
21.79 KB
and some of them have small size 18.19 KB so I don't think it is only the issue , and for the others it is not possible to split them , any suggestion? 
I am blocked to deploy our ecosystem because of those remaining contract

**Comment by bxpana** [comment] 2022-10-28 23:52
@deanpress and @amrshaban2005 @laukkw we updated our docs for how to handle contracts that are not deploying due to gas and the transaction failing. Mind checking this out and seeing if it helps resolve the issue? https://v2-docs.zksync.io/dev/developer-guides/contracts/contracts.html#note-on-factory-deps

**Comment by amrshaban2005** [comment] 2022-10-31 11:19
@bxpana 
I got this error after upgrade versions
`Transaction requires too much gas or exceed VM execution limits to commit on L1`
and the solution you proposed that split the contracts (5 contracts) is not doable for us, our platform has a lot of complex contracts and they are dependent on each other so that we can not do that

**Comment by bxpana** [comment] 2022-10-31 23:23
@amrshaban2005 ok let me see if we have any other solutions for something like this at the moment. I believe you have shared your contracts with Sisyfos on Discord is that correct?

**Comment by amrshaban2005** [comment] 2022-11-01 08:34
> @amrshaban2005 ok let me see if we have any other solutions for something like this at the moment. I believe you have shared your contracts with Sisyfos on Discord is that correct?

yes I did , waiting your response , thank you

**Comment by bxpana** [comment] 2022-11-02 18:17
@laukkw is this initial issue resolved now?

**Comment by bxpana** [comment] 2022-11-30 20:00
@deanpress and @amrshaban2005 closing this ticket for now. 

@amrshaban2005 we released an update that increased the ergs limit, have you tried recently to deploy your contract? If you are still getting the same error, please feel free to open another ticket to track the activity there.

**Closed by bxpana** 2022-11-30 20:00 UTC
Labels: in progress
